workflows:
  workflow-name:
    environment:
      groups:
        - appknox_credentials
      image: codemagic/android:latest
    scripts:
      - name: Checkout Code
        script: git clone https://github.com/avzz-19/mfva.git

      - name: Grant Execute Permission for Gradlew
        script: chmod +x gradlew

      - name: Build the App
        script: ./gradlew bundle

      - name: Upload AAB Artifact
        script: |
          cp app/build/outputs/bundle/debug/app.aab ./

      - name: Install Appknox Binary
        script: |
          curl -L https://github.com/appknox/appknox-go/releases/latest/download/appknox-`uname -s`-x86_64 > /usr/local/bin/appknox
          chmod +x /usr/local/bin/appknox 

      - name: Upload Binary to Appknox
        script: appknox upload ./app.aab

      - name: Check Vulnerability Risk Level
        script: appknox cicheck 72085 --risk_threshold HIGH
